eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: core-service

#server:
#  port: 8082

spring:
  boot:
    admin:
      client:
        url: http://localhost:9899
        username: kamron
        password: admin
        instance:
          name: core-service
