eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: http://${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 30
    
spring:
  boot:
    admin:
      client:
        url: http://monitoring-service:9899
        username: kamron
        password: admin
        instance:
          name: deposit-service
