spring:
  application:
    name: hello-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka
      
debug: true

management:
  endpoint:
    features:
      enabled: true
